export const CATEGORIES_GET_DATA = 'CATEGORIES_GET_DATA';
export const CATEGORY_GET_DATA = 'CATEGORY_GET_DATA';
export const CATEGORY_GET_PAGE_DATA = 'CATEGORY_GET_PAGE_DATA';
export const CATEGORY_APPLY_FILTER = 'CATEGORY_APPLY_FILTER';
export const SHOPPING_CART_ITEMS_COUNT = 'SHOPPING_CART_ITEMS_COUNT';
export const SHOPPING_CART_GET = 'SHOPPING_CART_GET';
export const SHOPPING_CART_ADD = 'SHOPPING_CART_ADD';
export const SHOPPING_CART_DROP_STATUS = 'SHOPPING_CART_DROP_STATUS';
export const SITE_GET_PAGE = 'SITE_GET_PAGE';
export const SHOPPING_CART_UPDATE_ITEM = 'SHOPPING_CART_UPDATE_ITEM';
export const SHOPPING_CHECKOUT = 'SHOPPING_CHECKOUT';
export const CATEGORY_SORT_BY = 'CATEGORY_SORT_BY';


